// This client was generated by Platformatic from an OpenAPI specification.

// The base URL for the API. This can be overridden by calling `setBaseUrl`.
let baseUrl = ''
// The default headers to send within each request. This can be overridden by calling `setDefaultHeaders`.
let defaultHeaders = {}
// The additional parameters you want to pass to the `fetch` instance.
let defaultFetchParams = {}
const defaultJsonType = { 'Content-type': 'application/json; charset=utf-8' }

function sanitizeUrl(url) {
  if (url.endsWith('/')) { return url.slice(0, -1) } else { return url }
}
/**  @type {import('./api-types.d.ts').Api['setBaseUrl']} */
export const setBaseUrl = (newUrl) => { baseUrl = sanitizeUrl(newUrl) }

/**  @type {import('./api-types.d.ts').Api['setDefaultHeaders']} */
export const setDefaultHeaders = (headers) => { defaultHeaders = headers }

/**  @type {import('./api-types.d.ts').Api['setDefaultFetchParams']} */
export const setDefaultFetchParams = (fetchParams) => { defaultFetchParams = fetchParams }

function headersToJSON(headers) {
  const output = {}
  headers.forEach((value, key) => {
    output[key] = value
  })
  return output
}

async function _getAgentsConfigs (url, request) {
  const queryParameters = ['limit', 'offset', 'totalCount', 'cursor', 'startAfter', 'endBefore', 'fields', 'where.createdAt.eq', 'where.createdAt.neq', 'where.createdAt.gt', 'where.createdAt.gte', 'where.createdAt.lt', 'where.createdAt.lte', 'where.createdAt.like', 'where.createdAt.ilike', 'where.createdAt.in', 'where.createdAt.nin', 'where.createdAt.contains', 'where.createdAt.contained', 'where.createdAt.overlaps', 'where.id.eq', 'where.id.neq', 'where.id.gt', 'where.id.gte', 'where.id.lt', 'where.id.lte', 'where.id.like', 'where.id.ilike', 'where.id.in', 'where.id.nin', 'where.id.contains', 'where.id.contained', 'where.id.overlaps', 'where.instructions.eq', 'where.instructions.neq', 'where.instructions.gt', 'where.instructions.gte', 'where.instructions.lt', 'where.instructions.lte', 'where.instructions.like', 'where.instructions.ilike', 'where.instructions.in', 'where.instructions.nin', 'where.instructions.contains', 'where.instructions.contained', 'where.instructions.overlaps', 'where.model.eq', 'where.model.neq', 'where.model.gt', 'where.model.gte', 'where.model.lt', 'where.model.lte', 'where.model.like', 'where.model.ilike', 'where.model.in', 'where.model.nin', 'where.model.contains', 'where.model.contained', 'where.model.overlaps', 'where.name.eq', 'where.name.neq', 'where.name.gt', 'where.name.gte', 'where.name.lt', 'where.name.lte', 'where.name.like', 'where.name.ilike', 'where.name.in', 'where.name.nin', 'where.name.contains', 'where.name.contained', 'where.name.overlaps', 'where.updatedAt.eq', 'where.updatedAt.neq', 'where.updatedAt.gt', 'where.updatedAt.gte', 'where.updatedAt.lt', 'where.updatedAt.lte', 'where.updatedAt.like', 'where.updatedAt.ilike', 'where.updatedAt.in', 'where.updatedAt.nin', 'where.updatedAt.contains', 'where.updatedAt.contained', 'where.updatedAt.overlaps', 'where.or', 'orderby.createdAt', 'orderby.id', 'orderby.instructions', 'orderby.model', 'orderby.name', 'orderby.updatedAt']
  const searchParams = new URLSearchParams()
  if (request.query) {
    queryParameters.forEach((qp) => {
      const queryValue = request.query?.[qp]
      if (queryValue) {
        if (Array.isArray(queryValue)) {
          queryValue.forEach((p) => searchParams.append(qp, p))
        } else {
          searchParams.append(qp, queryValue.toString())
        }
      }
      delete request.query?.[qp]
    })
  }

  const headers = {
    ...defaultHeaders
  }

  const response = await fetch(`${url}/agentsConfigs/?${searchParams.toString()}`, {
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [200]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

/**  @type {import('./api-types.d.ts').Api['getAgentsConfigs']} */
export const getAgentsConfigs = async (request) => {
  return await _getAgentsConfigs(baseUrl, request)
}
async function _createAgentsConfig (url, request) {
  const queryParameters = ['fields']
  const searchParams = new URLSearchParams()
  if (request.query) {
    queryParameters.forEach((qp) => {
      const queryValue = request.query?.[qp]
      if (queryValue) {
        if (Array.isArray(queryValue)) {
          queryValue.forEach((p) => searchParams.append(qp, p))
        } else {
          searchParams.append(qp, queryValue.toString())
        }
      }
      delete request.query?.[qp]
    })
  }

  const body = 'body' in request ? (request.body) : undefined
  const isFormData = body instanceof FormData
  const headers = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/agentsConfigs/?${searchParams.toString()}`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [200]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

/**  @type {import('./api-types.d.ts').Api['createAgentsConfig']} */
export const createAgentsConfig = async (request) => {
  return await _createAgentsConfig(baseUrl, request)
}
async function _updateAgentsConfigs (url, request) {
  const queryParameters = ['fields', 'where.createdAt.eq', 'where.createdAt.neq', 'where.createdAt.gt', 'where.createdAt.gte', 'where.createdAt.lt', 'where.createdAt.lte', 'where.createdAt.like', 'where.createdAt.ilike', 'where.createdAt.in', 'where.createdAt.nin', 'where.createdAt.contains', 'where.createdAt.contained', 'where.createdAt.overlaps', 'where.id.eq', 'where.id.neq', 'where.id.gt', 'where.id.gte', 'where.id.lt', 'where.id.lte', 'where.id.like', 'where.id.ilike', 'where.id.in', 'where.id.nin', 'where.id.contains', 'where.id.contained', 'where.id.overlaps', 'where.instructions.eq', 'where.instructions.neq', 'where.instructions.gt', 'where.instructions.gte', 'where.instructions.lt', 'where.instructions.lte', 'where.instructions.like', 'where.instructions.ilike', 'where.instructions.in', 'where.instructions.nin', 'where.instructions.contains', 'where.instructions.contained', 'where.instructions.overlaps', 'where.model.eq', 'where.model.neq', 'where.model.gt', 'where.model.gte', 'where.model.lt', 'where.model.lte', 'where.model.like', 'where.model.ilike', 'where.model.in', 'where.model.nin', 'where.model.contains', 'where.model.contained', 'where.model.overlaps', 'where.name.eq', 'where.name.neq', 'where.name.gt', 'where.name.gte', 'where.name.lt', 'where.name.lte', 'where.name.like', 'where.name.ilike', 'where.name.in', 'where.name.nin', 'where.name.contains', 'where.name.contained', 'where.name.overlaps', 'where.updatedAt.eq', 'where.updatedAt.neq', 'where.updatedAt.gt', 'where.updatedAt.gte', 'where.updatedAt.lt', 'where.updatedAt.lte', 'where.updatedAt.like', 'where.updatedAt.ilike', 'where.updatedAt.in', 'where.updatedAt.nin', 'where.updatedAt.contains', 'where.updatedAt.contained', 'where.updatedAt.overlaps', 'where.or']
  const searchParams = new URLSearchParams()
  if (request.query) {
    queryParameters.forEach((qp) => {
      const queryValue = request.query?.[qp]
      if (queryValue) {
        if (Array.isArray(queryValue)) {
          queryValue.forEach((p) => searchParams.append(qp, p))
        } else {
          searchParams.append(qp, queryValue.toString())
        }
      }
      delete request.query?.[qp]
    })
  }

  const body = 'body' in request ? (request.body) : undefined
  const isFormData = body instanceof FormData
  const headers = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/agentsConfigs/?${searchParams.toString()}`, {
    method: 'PUT',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [200]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

/**  @type {import('./api-types.d.ts').Api['updateAgentsConfigs']} */
export const updateAgentsConfigs = async (request) => {
  return await _updateAgentsConfigs(baseUrl, request)
}
async function _getAgentsConfigById (url, request) {
  const queryParameters = ['fields']
  const searchParams = new URLSearchParams()
  if (request.query) {
    queryParameters.forEach((qp) => {
      const queryValue = request.query?.[qp]
      if (queryValue) {
        if (Array.isArray(queryValue)) {
          queryValue.forEach((p) => searchParams.append(qp, p))
        } else {
          searchParams.append(qp, queryValue.toString())
        }
      }
      delete request.query?.[qp]
    })
  }

  const headers = {
    ...defaultHeaders
  }

  const response = await fetch(`${url}/agentsConfigs/${request.path['id']}?${searchParams.toString()}`, {
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [200]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

/**  @type {import('./api-types.d.ts').Api['getAgentsConfigById']} */
export const getAgentsConfigById = async (request) => {
  return await _getAgentsConfigById(baseUrl, request)
}
async function _updateAgentsConfig (url, request) {
  const queryParameters = ['fields']
  const searchParams = new URLSearchParams()
  if (request.query) {
    queryParameters.forEach((qp) => {
      const queryValue = request.query?.[qp]
      if (queryValue) {
        if (Array.isArray(queryValue)) {
          queryValue.forEach((p) => searchParams.append(qp, p))
        } else {
          searchParams.append(qp, queryValue.toString())
        }
      }
      delete request.query?.[qp]
    })
  }

  const body = 'body' in request ? (request.body) : undefined
  const isFormData = body instanceof FormData
  const headers = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/agentsConfigs/${request.path['id']}?${searchParams.toString()}`, {
    method: 'PUT',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [200]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

/**  @type {import('./api-types.d.ts').Api['updateAgentsConfig']} */
export const updateAgentsConfig = async (request) => {
  return await _updateAgentsConfig(baseUrl, request)
}
async function _deleteAgentsConfigs (url, request) {
  const queryParameters = ['fields']
  const searchParams = new URLSearchParams()
  if (request.query) {
    queryParameters.forEach((qp) => {
      const queryValue = request.query?.[qp]
      if (queryValue) {
        if (Array.isArray(queryValue)) {
          queryValue.forEach((p) => searchParams.append(qp, p))
        } else {
          searchParams.append(qp, queryValue.toString())
        }
      }
      delete request.query?.[qp]
    })
  }

  const body = 'body' in request ? (request.body) : undefined
  const isFormData = body instanceof FormData
  const headers = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/agentsConfigs/${request.path['id']}?${searchParams.toString()}`, {
    method: 'DELETE',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [200]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

/**  @type {import('./api-types.d.ts').Api['deleteAgentsConfigs']} */
export const deleteAgentsConfigs = async (request) => {
  return await _deleteAgentsConfigs(baseUrl, request)
}
async function _getExample (url, request) {
  const headers = {
    ...defaultHeaders
  }

  const response = await fetch(`${url}/example`, {
    headers,
    ...defaultFetchParams
  })

  const textResponses = [200]
  if (textResponses.includes(response.status)) {
    return {
      statusCode: response.status,
      headers: headersToJSON(response.headers),
      body: await response.text()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

/**  @type {import('./api-types.d.ts').Api['getExample']} */
export const getExample = async (request) => {
  return await _getExample(baseUrl, request)
}
export default function build (url, options) {
  url = sanitizeUrl(url)
  if (options?.headers) {
    defaultHeaders = options.headers
  }
  return {
    getAgentsConfigs: _getAgentsConfigs.bind(url, ...arguments),
    createAgentsConfig: _createAgentsConfig.bind(url, ...arguments),
    updateAgentsConfigs: _updateAgentsConfigs.bind(url, ...arguments),
    getAgentsConfigById: _getAgentsConfigById.bind(url, ...arguments),
    updateAgentsConfig: _updateAgentsConfig.bind(url, ...arguments),
    deleteAgentsConfigs: _deleteAgentsConfigs.bind(url, ...arguments),
    getExample: _getExample.bind(url, ...arguments)
  }
}